### ISSUE TITLE
nodos new generate an "undefined" directory

### ISSUE THREAD

**Issue by morphizm** [nodosjs/nodos#117]
nodos new generate an "undefined" directory.
<img width="1228" alt="Screenshot 2020-10-11 at 20 35 10" src="https://user-images.githubusercontent.com/52827241/95685587-6392d580-0c01-11eb-9678-abca4b3ba739.png">

**Comment by lazycoder9** [comment]
Этот баг уже починен, но мы не зарелизили его. Фикс можно проверить если генерировать новое приложение напрямую из nodos-cli
```
./nodos/packages/nodos-cli/bin/nodos.js new ...
```
